test image name staging

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -10,99 +10,99 @@ on:
     branches:
       - master
 jobs:
-  uncheck-integration-test:
-    name: Mark integration test as not run
-    runs-on: ubuntu-20.04
-    if: github.event_name == 'pull_request'
-    steps:
-      - id: get-pr-body
-        name: Get the current PR body
-        uses: jwalton/gh-find-current-pr@v1
-        with:
-          state: open
+  # uncheck-integration-test:
+  #   name: Mark integration test as not run
+  #   runs-on: ubuntu-20.04
+  #   if: github.event_name == 'pull_request'
+  #   steps:
+  #     - id: get-pr-body
+  #       name: Get the current PR body
+  #       uses: jwalton/gh-find-current-pr@v1
+  #       with:
+  #         state: open
 
-      - id: create-unchecked-pr-body
-        name: Create unchecked PR body
-        run: |-
-          UNCHECKED_BODY=$(sed 's/- \[[Xx]\] Started end-to-end tests on the latest commit./- \[ \] Started end-to-end tests on the latest commit./' <<\EOF
-          ${{ steps.get-pr-body.outputs.body }}
-          EOF
-          )
+  #     - id: create-unchecked-pr-body
+  #       name: Create unchecked PR body
+  #       run: |-
+  #         UNCHECKED_BODY=$(sed 's/- \[[Xx]\] Started end-to-end tests on the latest commit./- \[ \] Started end-to-end tests on the latest commit./' <<\EOF
+  #         ${{ steps.get-pr-body.outputs.body }}
+  #         EOF
+  #         )
 
-          UNCHECKED_BODY="${UNCHECKED_BODY//'%'/'%25'}"
-          UNCHECKED_BODY="${UNCHECKED_BODY//$'\n'/'%0A'}"
-          UNCHECKED_BODY="${UNCHECKED_BODY//$'\r'/'%0D'}"
+  #         UNCHECKED_BODY="${UNCHECKED_BODY//'%'/'%25'}"
+  #         UNCHECKED_BODY="${UNCHECKED_BODY//$'\n'/'%0A'}"
+  #         UNCHECKED_BODY="${UNCHECKED_BODY//$'\r'/'%0D'}"
 
-          echo "Unchecked PR body"
-          echo $UNCHECKED_BODY
+  #         echo "Unchecked PR body"
+  #         echo $UNCHECKED_BODY
 
-          echo "::set-output name=body::$UNCHECKED_BODY"
+  #         echo "::set-output name=body::$UNCHECKED_BODY"
 
-      - id: uncheck-integration-checkbox
-        name: Uncheck the integration checkbox
-        uses: tzkhan/pr-update-action@v2
-        with:
-          repo-token: "${{ secrets.API_TOKEN_GITHUB }}"
-          head-branch-regex: "${{ github.head_ref }}"
-          lowercase-branch: false
-          body-template: "${{  steps.create-unchecked-pr-body.outputs.body }}"
-          body-update-action: 'replace'
+  #     - id: uncheck-integration-checkbox
+  #       name: Uncheck the integration checkbox
+  #       uses: tzkhan/pr-update-action@v2
+  #       with:
+  #         repo-token: "${{ secrets.API_TOKEN_GITHUB }}"
+  #         head-branch-regex: "${{ github.head_ref }}"
+  #         lowercase-branch: false
+  #         body-template: "${{  steps.create-unchecked-pr-body.outputs.body }}"
+  #         body-update-action: 'replace'
 
-  test:
-    name: Run tests
-    runs-on: ubuntu-20.04
-    env:
-      CI: "true"
-    steps:
+  # test:
+  #   name: Run tests
+  #   runs-on: ubuntu-20.04
+  #   env:
+  #     CI: "true"
+  #   steps:
 
-    - id: setup-node
-      uses: actions/setup-node@v2
-      with:
-        node-version: '14'
+  #   - id: setup-node
+  #     uses: actions/setup-node@v2
+  #     with:
+  #       node-version: '14'
 
-    - id: checkout
-      name: Check out source code
-      uses: actions/checkout@v2
+  #   - id: checkout
+  #     name: Check out source code
+  #     uses: actions/checkout@v2
 
-    - id: cache-seek
-      name: Check for npm cache hit
-      uses: c-hive/gha-npm-cache@v1
+  #   - id: cache-seek
+  #     name: Check for npm cache hit
+  #     uses: c-hive/gha-npm-cache@v1
 
-    - id: install
-      name: Install dependencies
-      run: |-
-        echo "Running CI with "
-        echo "Node version: $(node --version)"
-        echo "NPM version: $(npm --version)"
+  #   - id: install
+  #     name: Install dependencies
+  #     run: |-
+  #       echo "Running CI with "
+  #       echo "Node version: $(node --version)"
+  #       echo "NPM version: $(npm --version)"
 
-        git config --global url."https://".insteadOf ssh://
-        npm ci
+  #       git config --global url."https://".insteadOf ssh://
+  #       npm ci
 
-    - id: test-codecov
-      name: Run unit tests with coverage
-      uses: mattallty/jest-github-action@v1
-      env:
-        AWS_DEFAULT_REGION: 'eu-west-1'
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        test-command: "npm run coverage"
-        coverage-comment: false
+  #   - id: test-codecov
+  #     name: Run unit tests with coverage
+  #     uses: mattallty/jest-github-action@v1
+  #     env:
+  #       AWS_DEFAULT_REGION: 'eu-west-1'
+  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     with:
+  #       test-command: "npm run coverage"
+  #       coverage-comment: false
 
-    - name: Upload coverage to Codecov
-      uses: codecov/codecov-action@v1
+  #   - name: Upload coverage to Codecov
+  #     uses: codecov/codecov-action@v1
 
   build-docker:
     name: Build Docker container
     runs-on: ubuntu-20.04
-    needs: test
+    # needs: test
     outputs:
       ref-id: ${{ steps.ref.outputs.ref-id }}
       image-tag: ${{ steps.ref.outputs.image-tag }}
       timestamp: ${{ steps.ref.outputs.timestamp }}
     steps:
-      - id: checkout
-        name: Check out source code
-        uses: actions/checkout@v2
+      # - id: checkout
+      #   name: Check out source code
+      #   uses: actions/checkout@v2
 
       - id: ref
         name: Format docker tag and repository name.
@@ -153,49 +153,49 @@ jobs:
           IMAGE_REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F '/' '{print $2}')
           echo "::set-output name=repo-name::$IMAGE_REPO_NAME"
 
-      - id: set-up-creds
-        name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: eu-west-1
+      # - id: set-up-creds
+      #   name: Configure AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1
+      #   with:
+      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: eu-west-1
 
-      - id: login-ecr
-        name: Login to Amazon ECR
-        uses: aws-actions/amazon-ecr-login@v1
+      # - id: login-ecr
+      #   name: Login to Amazon ECR
+      #   uses: aws-actions/amazon-ecr-login@v1
 
-      - id: create-ecr-registry
-        name: Create an ECR repository (if needed)
-        # This will fail if the registry already exists, which is fine. If there is some other
-        # error, the `push` step will fail instead.
-        continue-on-error: true
-        run: |-
-          aws ecr create-repository --repository-name $REPO_NAME --image-tag-mutability IMMUTABLE
-        env:
-          REPO_NAME: ${{ steps.ref.outputs.repo-name }}
+      # - id: create-ecr-registry
+      #   name: Create an ECR repository (if needed)
+      #   # This will fail if the registry already exists, which is fine. If there is some other
+      #   # error, the `push` step will fail instead.
+      #   continue-on-error: true
+      #   run: |-
+      #     aws ecr create-repository --repository-name $REPO_NAME --image-tag-mutability IMMUTABLE
+      #   env:
+      #     REPO_NAME: ${{ steps.ref.outputs.repo-name }}
 
-      - id: build
-        name: Build Docker image
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          file: ./Dockerfile
-          platforms: linux/amd64
-          tags: ${{ format('{0}/{1}:{2}', steps.login-ecr.outputs.registry, steps.ref.outputs.repo-name, steps.ref.outputs.image-tag) }}
-          push: false
+      # - id: build
+      #   name: Build Docker image
+      #   uses: docker/build-push-action@v2
+      #   with:
+      #     context: .
+      #     file: ./Dockerfile
+      #     platforms: linux/amd64
+      #     tags: ${{ format('{0}/{1}:{2}', steps.login-ecr.outputs.registry, steps.ref.outputs.repo-name, steps.ref.outputs.image-tag) }}
+      #     push: false
 
       - id: push
         name: Push docker image to ECR
         run: |-
           echo Pushing image $IMAGE_NAME to ECR.
-          docker push $IMAGE_NAME
+          # docker push $IMAGE_NAME
 
           if [ ! -z "$TIMESTAMP" ]; then
             echo Pushing timestamped $IMAGE_NAME to ECR
 
-            docker tag $IMAGE_NAME $IMAGE_NAME-$TIMESTAMP
-            docker push $IMAGE_NAME-$TIMESTAMP
+            # docker tag $IMAGE_NAME $IMAGE_NAME-$TIMESTAMP
+            # docker push $IMAGE_NAME-$TIMESTAMP
           fi
         env:
           IMAGE_NAME: ${{ format('{0}/{1}:{2}', steps.login-ecr.outputs.registry, steps.ref.outputs.repo-name, steps.ref.outputs.image-tag) }}
@@ -210,21 +210,21 @@ jobs:
       matrix:
         environment: ['production', 'staging', 'develop']
     steps:
-      - id: checkout
-        name: Check out source code
-        uses: actions/checkout@v2
+      # - id: checkout
+      #   name: Check out source code
+      #   uses: actions/checkout@v2
 
-      - id: setup-aws
-        name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: eu-west-1
+      # - id: setup-aws
+      #   name: Configure AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1
+      #   with:
+      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: eu-west-1
 
-      - id: login-ecr
-        name: Login to Amazon ECR
-        uses: aws-actions/amazon-ecr-login@v1
+      # - id: login-ecr
+      #   name: Login to Amazon ECR
+      #   uses: aws-actions/amazon-ecr-login@v1
 
       - id: fill-metadata
         name: Fill out a new HelmRelease resource
@@ -319,98 +319,98 @@ jobs:
           TIMESTAMP: ${{ steps.build-docker.outputs.timestamp }}
           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
 
-      - id: disable-admin-enforcement
-        name: Temporarily disable admin enforcement
-        uses: benjefferies/branch-protection-bot@1.0.7
-        with:
-          access_token: ${{ secrets.API_TOKEN_GITHUB }}
-          owner: ${{ github.repository_owner }}
-          repo: iac
-          enforce_admins: false
-          retries: 8
+  #     - id: disable-admin-enforcement
+  #       name: Temporarily disable admin enforcement
+  #       uses: benjefferies/branch-protection-bot@1.0.7
+  #       with:
+  #         access_token: ${{ secrets.API_TOKEN_GITHUB }}
+  #         owner: ${{ github.repository_owner }}
+  #         repo: iac
+  #         enforce_admins: false
+  #         retries: 8
 
-      - name: Push production/develop template to releases
-        if:
-          (matrix.environment == 'production' && github.event_name == 'release' && github.event.action == 'released') || (matrix.environment == 'develop' && github.event_name == 'push')
-        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-        with:
-          source_file: '${{ steps.fill-metadata.outputs.deployment-name }}.yaml'
-          destination_repo: '${{ github.repository_owner }}/releases'
-          destination_folder: '${{ steps.fill-metadata.outputs.kubernetes-env }}'
-          user_email: 'ci@biomage.net'
-          user_name: 'Biomage CI/CD'
+  #     - name: Push production/develop template to releases
+  #       if:
+  #         (matrix.environment == 'production' && github.event_name == 'release' && github.event.action == 'released') || (matrix.environment == 'develop' && github.event_name == 'push')
+  #       uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
+  #       env:
+  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+  #       with:
+  #         source_file: '${{ steps.fill-metadata.outputs.deployment-name }}.yaml'
+  #         destination_repo: '${{ github.repository_owner }}/releases'
+  #         destination_folder: '${{ steps.fill-metadata.outputs.kubernetes-env }}'
+  #         user_email: 'ci@biomage.net'
+  #         user_name: 'Biomage CI/CD'
 
-      - name: Change name of deployment file for staging deployment
-        if:
-          (github.event_name == 'pull_request' || github.event_name == 'push') && matrix.environment == 'staging'
-        env:
-          DEPLOYMENT_NAME: ${{ steps.fill-metadata.outputs.deployment-name }}
-          REF_ID: ${{ needs.build-docker.outputs.ref-id }}
-        run: |-
-          mv $DEPLOYMENT_NAME.yaml $REF_ID.yaml
+  #     - name: Change name of deployment file for staging deployment
+  #       if:
+  #         (github.event_name == 'pull_request' || github.event_name == 'push') && matrix.environment == 'staging'
+  #       env:
+  #         DEPLOYMENT_NAME: ${{ steps.fill-metadata.outputs.deployment-name }}
+  #         REF_ID: ${{ needs.build-docker.outputs.ref-id }}
+  #       run: |-
+  #         mv $DEPLOYMENT_NAME.yaml $REF_ID.yaml
 
-      - name: Push staging deployment template to releases
-        if:
-          (github.event_name == 'pull_request' || github.event_name == 'push') && matrix.environment == 'staging'
-        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-        with:
-          source_file: ${{ needs.build-docker.outputs.ref-id }}.yaml
-          destination_repo: '${{ github.repository_owner }}/flux-v2-migration'
-          destination_folder: 'staging-candidates/${{ steps.fill-metadata.outputs.deployment-name }}'
-          user_email: 'ci@biomage.net'
-          user_name: 'Biomage CI/CD'
+  #     - name: Push staging deployment template to releases
+  #       if:
+  #         (github.event_name == 'pull_request' || github.event_name == 'push') && matrix.environment == 'staging'
+  #       uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
+  #       env:
+  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+  #       with:
+  #         source_file: ${{ needs.build-docker.outputs.ref-id }}.yaml
+  #         destination_repo: '${{ github.repository_owner }}/flux-v2-migration'
+  #         destination_folder: 'staging-candidates/${{ steps.fill-metadata.outputs.deployment-name }}'
+  #         user_email: 'ci@biomage.net'
+  #         user_name: 'Biomage CI/CD'
 
-      - name: Push migrations into iac
-        if:
-          (matrix.environment == 'production' && github.event_name == 'release' && github.event.action == 'released') || (matrix.environment == 'develop' && github.event_name == 'push')
-        uses: cpina/github-action-push-to-another-repository@main
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-        with:
-          source-directory: 'src/sql/migrations'
-          destination-github-username: '${{ github.repository_owner }}'
-          destination-repository-name: 'iac'
-          user-email: 'ci@biomage.net'
-          target-branch: master
-          target-directory: 'migrations/sql/${{ steps.fill-metadata.outputs.kubernetes-env }}'
+  #     - name: Push migrations into iac
+  #       if:
+  #         (matrix.environment == 'production' && github.event_name == 'release' && github.event.action == 'released') || (matrix.environment == 'develop' && github.event_name == 'push')
+  #       uses: cpina/github-action-push-to-another-repository@main
+  #       env:
+  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+  #       with:
+  #         source-directory: 'src/sql/migrations'
+  #         destination-github-username: '${{ github.repository_owner }}'
+  #         destination-repository-name: 'iac'
+  #         user-email: 'ci@biomage.net'
+  #         target-branch: master
+  #         target-directory: 'migrations/sql/${{ steps.fill-metadata.outputs.kubernetes-env }}'
 
-      - id: enable-admin-enforcement
-        name: Re-enable admin enforcement
-        uses: benjefferies/branch-protection-bot@1.0.7
-        if: always()
-        with:
-          access_token: ${{ secrets.API_TOKEN_GITHUB }}
-          owner: ${{ github.repository_owner }}
-          repo: iac
-          enforce_admins: true
-          retries: 8
+  #     - id: enable-admin-enforcement
+  #       name: Re-enable admin enforcement
+  #       uses: benjefferies/branch-protection-bot@1.0.7
+  #       if: always()
+  #       with:
+  #         access_token: ${{ secrets.API_TOKEN_GITHUB }}
+  #         owner: ${{ github.repository_owner }}
+  #         repo: iac
+  #         enforce_admins: true
+  #         retries: 8
 
-  ready-to-merge:
-    name: Ready for merging
-    runs-on: ubuntu-20.04
-    needs: deploy
-    steps:
-      - id: ready-to-merge
-        name: Signal readiness to merge
-        run: |-
-          exit 0
+  # ready-to-merge:
+  #   name: Ready for merging
+  #   runs-on: ubuntu-20.04
+  #   needs: deploy
+  #   steps:
+  #     - id: ready-to-merge
+  #       name: Signal readiness to merge
+  #       run: |-
+  #         exit 0
 
-  report-if-failed:
-    name: Report if workflow failed
-    runs-on: ubuntu-20.04
-    needs: [test, build-docker, deploy]
-    if: failure() && github.ref == 'refs/heads/master'
-    steps:
-      - id: send-to-slack
-        name: Send failure notification to Slack on failure
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.WORKFLOW_STATUS_BOT_TOKEN }}
-        uses: voxmedia/github-action-slack-notify-build@v1
-        with:
-          channel: workflow-failures
-          status: FAILED
-          color: danger
+  # report-if-failed:
+  #   name: Report if workflow failed
+  #   runs-on: ubuntu-20.04
+  #   needs: [test, build-docker, deploy]
+  #   if: failure() && github.ref == 'refs/heads/master'
+  #   steps:
+  #     - id: send-to-slack
+  #       name: Send failure notification to Slack on failure
+  #       env:
+  #         SLACK_BOT_TOKEN: ${{ secrets.WORKFLOW_STATUS_BOT_TOKEN }}
+  #       uses: voxmedia/github-action-slack-notify-build@v1
+  #       with:
+  #         channel: workflow-failures
+  #         status: FAILED
+  #         color: danger
